services:
  app:
    build: .
    container_name: flask-client-camera
    command: python emotion_detection.py
    #command: gunicorn -b 0.0.0.0:5000 --worker-class eventlet -w 1 emotion_detection:app
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - 8080:5000
    volumes:
      - .:/app
